# **Data Preprocess**

1) **Anomolly in Data.**
   - Outliers.
   - Unbalanced Structure.
   - Extra Strings/Data.
   - Invalid Data Types.
  &nbsp;
  <br>

2) **Missing Values.**
3) **Feature/Column Scaling (Normliztion)**
  > Feature Scaling is a method to limit the range of variables so that they can be compared on common grounds.It helps Algorithms to coverage faster and modal perform better ,especially for modals like regression, logistic regression and supprt vector machines.
  
  #### **Methods**
- Min Max Scaling.
- Standard Scaling (Z-Score Normalization)
- Robost Scaling.
- Logarthimic Scaling.


#### **Min Max Scaling.**

X`=X-min(X) / max(X)-min(X)    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       (0<=X<=1)


#### **Standard Scaling.**

X`=X-mean(X) / std(X)   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           (-3<=X<=3)
- Normal distributions follow the empirical rule, also called the 68-95-99.7 rule
    - (-1<=X<=1)   68% Data lie in this range.
    - (-2<=X<=2)   95% Data lie in this range.
    - (-3<=X<=3)   99.7% Data lie in this range.

#### **Robost Scaling.**

X`=X-median(X) / IQR(X)    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       (negtive-<=X<=Postive)

-It gives Values in between  Percetile 25%  to 75% Percentile.

#### **Logarthimic Scaling..**

X`=Take log10 of data.

In [59]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [60]:
data={
    'Value':[10,20,30,40,50]
}
df=pd.DataFrame(data)
df

   Value
0     10
1     20
2     30
3     40
4     50

# **Min-Max Scalar**

In [61]:
# Method 1
# scalar=MinMaxScaler()
# df['Scaled Value']=scalar.fit_transform(df['Value'].values.reshape(-1,1))
# df

# Method 2
df['Scaled Value Min Max']=MinMaxScaler().fit_transform(df[['Value']])
df

   Value  Scaled Value Min Max
0     10                  0.00
1     20                  0.25
2     30                  0.50
3     40                  0.75
4     50                  1.00

# **Standard Scalar**

In [62]:
from sklearn.preprocessing import StandardScaler

# Method 1
# scalar=StandardScaler()
# df['Scaled Value']=scalar.fit_transform(df['Value'].values.reshape(-1,1))
# df

# Method 2
df['Scaled Value Standard']=StandardScaler().fit_transform(df[['Value']])
df

   Value  Scaled Value Min Max  Scaled Value Standard
0     10                  0.00              -1.414214
1     20                  0.25              -0.707107
2     30                  0.50               0.000000
3     40                  0.75               0.707107
4     50                  1.00               1.414214

# **Robost Scalar**

In [63]:
from sklearn.preprocessing import RobustScaler
# scalar=RobustScaler()
# df['Scaled Value Robost']=scalar.fit_transform(df['Value'].values.reshape(-1,1))
# df

# Method 2
df['Scaled Value Robost']=RobustScaler().fit_transform(df[['Value']])
df

   Value  Scaled Value Min Max  Scaled Value Standard  Scaled Value Robost
0     10                  0.00              -1.414214                 -1.0
1     20                  0.25              -0.707107                 -0.5
2     30                  0.50               0.000000                  0.0
3     40                  0.75               0.707107                  0.5
4     50                  1.00               1.414214                  1.0

# **Logarthimic Scalar**

In [64]:

df['Scaled Value Logartimic']=np.log(df['Value'])
df['Scaled Value Logartimic2']=np.log(df['Value'])
df['Scaled Value Logartimic10']=np.log(df['Value'])

df

,Value,Scaled Value Min Max,Scaled Value Standard,Scaled Value Robost,Scaled Value Logartimic,Scaled Value Logartimic2,Scaled Value Logartimic10
0,10,0.00,-1.414214,-1.0,2.302585,2.302585,2.302585
1,20,0.25,-0.707107,-0.5,2.995732,2.995732,2.995732
2,30,0.50,0.000000,0.0,3.401197,3.401197,3.401197
3,40,0.75,0.707107,0.5,3.688879,3.688879,3.688879
4,50,1.00,1.414214,1.0,3.912023,3.912023,3.912023

# **Feature Encoding.**

- It only performs on Categorical Columns.

 #### **Methods**
- One Hot Encoding.
- Label Encoding.
- Ordinal Encoding.

# **One Hot Encoding**

In [65]:
data={
    'color':['Red','Blue','Yellow','Black']
}

# One Hot Encoding
df=pd.DataFrame(data)
one_hot_encoded_data=pd.get_dummies(df,columns=['color'])

# **Label Encoding**

In [66]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
# Method 1
# Encoder=LabelEncoder()
# df['Labeled Encoder']=scalar.fit_transform(df['color'].values.reshape(-1,1))
# df

# # Method 2
# df['Labeled Encoder']=LabelEncoder().fit_transform(df[['color']])
# df

In [67]:
from sklearn.preprocessing import OrdinalEncoder
data={
    'Size':['small','medium','large','small','medium','large','small']
}
df=pd.DataFrame(data)
# Method 1
# encoder=OrdinalEncoder(categories=[['small','medium','large']])
# df['Ordinal Encoder']=encoder.fit_transform(df['Size'].values.reshape(-1,1))
# df

# Method 2
OrdinalEncoder(categories=[['small','medium','large']])
df['Ordinal Encoder']=OrdinalEncoder(categories=[['small','medium','large']]).fit_transform(df[['Size']])
df

     Size  Ordinal Encoder
0   small              0.0
1  medium              1.0
2   large              2.0
3   small              0.0
4  medium              1.0
5   large              2.0
6   small              0.0